import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import {Raleway} from 'next/font/google'
import './globals.css'
import Footer from './modules/footer/footer'
import Header from './modules/header/header'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${raleway.className} flex flex-col bg-white`}>
        <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
